Version = 0
Id = "00000000-0000-0000-0000-000000000000"
Name = "simple"
PropertiesSchema = "schema_properties.json"
HashType = "sha2-256"

[Properties]
  description = "a bogus test holochain"
  language = "en"

[BasedOn]

[Zomes]
  [Zomes.jsZome]
    Name = "jsZome"
    Description = "this is a javascript test zome"
    Code = "zome_jsZome.js"
    NucleusType = "js"
    [Zomes.jsZome.CodeHash]
    [Zomes.jsZome.Entries]
      [Zomes.jsZome.Entries.myOdds]
        Name = "myOdds"
        DataFormat = "js"
        Schema = ""
        [Zomes.jsZome.Entries.myOdds.SchemaHash]
  [Zomes.myZome]
    Name = "myZome"
    Description = "this is a zygomas test zome"
    Code = "zome_myZome.zy"
    NucleusType = "zygo"
    [Zomes.myZome.CodeHash]
    [Zomes.myZome.Entries]
      [Zomes.myZome.Entries.myData]
        Name = "myData"
        DataFormat = "zygo"
        Schema = ""
        [Zomes.myZome.Entries.myData.SchemaHash]
      [Zomes.myZome.Entries.primes]
        Name = "primes"
        DataFormat = "json"
        Schema = ""
        [Zomes.myZome.Entries.primes.SchemaHash]
      [Zomes.myZome.Entries.profile]
        Name = "profile"
        DataFormat = "json"
        Schema = "schema_profile.json"
        [Zomes.myZome.Entries.profile.SchemaHash]
